from django.urls import path

from . import views
app_name = 'site_link'
urlpatterns = [
    path('',views.index, name='index'),
    path('CEM/', views.CEM, name='CEM'),
    path('public/',views.index_2, name='index_2'),
    path('write/public/', views.create_2, name='create_2'),
    path('<int:pk>/public/', views.detail_2, name='detail_2'),
    path('<int:pk>/edit/public/', views.update_2, name='update_2'),
    path('<int:pk>/delete/public/', views.delete_2, name='delete_2'),
    path('gov/',views.index_3, name='index_3'),
    path('write/gov/', views.create_3, name='create_3'),
    path('<int:pk>/gov/', views.detail_3, name='detail_3'),
    path('<int:pk>/edit/gov/', views.update_3, name='update_3'),
    path('<int:pk>/delete/gov/', views.delete_3, name='delete_3'),
    path('insitute/',views.index_4, name='index_4'),
    path('write/insitute/', views.create_4, name='create_4'),
    path('<int:pk>/insitute/', views.detail_4, name='detail_4'),
    path('<int:pk>/edit/insitute/', views.update_4, name='update_4'),
    path('<int:pk>/delete/insitute/', views.delete_4, name='delete_4'),
    path('oversea/',views.index_5, name='index_5'),
    path('write/oversea/', views.create_5, name='create_5'),
    path('<int:pk>/oversea/', views.detail_5, name='detail_5'),
    path('<int:pk>/edit/oversea/', views.update_5, name='update_5'),
    path('<int:pk>/delete/oversea/', views.delete_5, name='delete_5'),
    path('other/',views.index_6, name='index_6'),
    path('write/other/', views.create_6, name='create_6'),
    path('<int:pk>/other/', views.detail_6, name='detail_6'),
    path('<int:pk>/edit/other/', views.update_6, name='update_6'),
    path('<int:pk>/delete/other/', views.delete_6, name='delete_6'),
    path('write/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]
