# Generated by Django 3.2.7 on 2021-09-29 21:22

from django.db import migrations, models
import pj_board.models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pj_post',
            old_name='subject',
            new_name='title',
        ),
        migrations.AddField(
            model_name='pj_post',
            name='photo',
            field=models.ImageField(blank=True, upload_to=pj_board.models.get_file_path),
        ),
    ]
