# Generated by Django 3.2.7 on 2021-10-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pj_board', '0002_auto_20210930_0622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pj_post',
            options={'verbose_name': 'pj_board_civ', 'verbose_name_plural': 'pj_board_civ'},
        ),
        migrations.AlterModelTable(
            name='pj_post',
            table='pj_board_civ',
        ),
    ]
