# Generated by Django 3.2.7 on 2021-10-01 16:54

from django.db import migrations, models
import pj_board.models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_board', '0003_auto_20211001_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pj_post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=pj_board.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='pj_post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
    ]
