# Generated by Django 3.2.7 on 2021-10-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_board', '0004_auto_20211002_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pj_post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pj_post',
            name='create_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pj_post',
            name='front_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pj_post',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='제목'),
        ),
    ]
