# Generated by Django 3.2.7 on 2021-10-01 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pj_board', '0005_auto_20211002_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pj_post',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
