# Generated by Django 3.2.7 on 2021-10-01 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pj_board', '0006_alter_pj_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pj_post',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
