# Generated by Django 3.2.7 on 2021-10-05 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pj_board', '0007_alter_pj_post_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pj_post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
