"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ymfb8=x#3qf6y)^sple8@&y-1@89q7u3^0z558m%(e!w#=lqjv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['52.78.144.114', 'scem.uos.ac.kr']


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_summernote',
]

PROJECT_APPS = [
    'pj_board.apps.PjBoardConfig',
    'pj_board_gov.apps.PjBoardGovConfig',
    'site_link.apps.SiteLinkConfig',
    'scem.apps.ScemConfig',
    'reserch_pj.apps.ReserchPjConfig',
    'professor.apps.ProfessorConfig',
    'paper_patent.apps.PaperPatentConfig',
    'notice.apps.NoticeConfig',
    'photo.apps.PhotoConfig',
    'free.apps.FreeConfig',
    'reference_board.apps.ReferenceBoardConfig',
    'seminar.apps.SeminarConfig',
    'QA.apps.QaConfig',
    'Q_A.apps.QAConfig',
    'member_board_MA.apps.MemberBoardMaConfig',
    'member_board_Phd.apps.MemberBoardPhdConfig',
    'member_board_alum_MA.apps.MemberBoardAlumMaConfig',
    'member_board_alum_Phd.apps.MemberBoardAlumPhdConfig',
    'member_board_alum_MA_city.apps.MemberBoardAlumMaCityConfig',
    'member_board_alum_special.apps.MemberBoardAlumSpecialConfig',
    'kor_conference.apps.KorConferenceConfig',
    'kor_jounal.apps.KorJounalConfig',
    'kor_thesis.apps.KorThesisConfig',
    'world_jounal.apps.WorldJounalConfig',
    'thesis_ma.apps.ThesisMaConfig',
    'world_conference.apps.WorldConferenceConfig',
    'property_1.apps.Property1Config',
    'property_2.apps.Property2Config',
    'property_3.apps.Property3Config',
    'professor_hyun_1',
    'professor_hyun_2',
    'professor_hyun_3',
    'professor_hyun_4',
    'professor_hyun_5',
    'professor_hyun_6',
    'professor_hyun_7',
    'professor_hyun_8',
]

INSTALLED_APPS = DJANGO_APPS + PROJECT_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'cemuos',
        'USER': 'dbmasteruser',
        'PASSWORD': 'CSEgp%[kS6[Cf{zzY&UdcnTb:k1$`-Yv',
        'HOST': 'ls-5734b79e30eddb1ef8aee9b4659aada0570a9ed3.cbqucunmt92t.ap-northeast-2.rds.amazonaws.com',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
# MEDIAFILES_DIRS = [
#     BASE_DIR / 'media',
# ]
MEIDA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
X_FRAME_OPTIONS = 'SAMEORIGIN'

LOGIN_REDIRECT_URL = '/'
# 로그아웃시 이동하는 URL
LOGOUT_REDIRECT_URL = '/'

# 로깅설정
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'formatters': {
        'django.server': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[{server_time}] {message}',
            'style': '{',
        },
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
        },
        'django.server': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'django.server',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'file': {
            'level': 'INFO',
            'filters': ['require_debug_false'],
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs/mysite.log',
            'maxBytes': 1024*1024*5,  # 5 MB
            'backupCount': 5,
            'formatter': 'standard',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'mail_admins', 'file'],
            'level': 'INFO',
        },
        'django.server': {
            'handlers': ['django.server'],
            'level': 'INFO',
            'propagate': False,
        },
        'cemuos': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
    }
}
SUMMERNOTE_CONFIG = {
    'attachment_filesize_limit': 70 * 1024 * 1024
}